"""initial

Revision ID: af569a8cca8a
Revises: 
Create Date: 2023-04-27 13:25:34.794112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af569a8cca8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxi_fare',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.TIMESTAMP(), nullable=False),
    sa.Column('fare_amount', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('pickup_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('pickup_longitude', sa.DECIMAL(precision=18, scale=15), nullable=False),
    sa.Column('pickup_latitude', sa.DECIMAL(precision=18, scale=15), nullable=False),
    sa.Column('dropoff_longitude', sa.DECIMAL(precision=18, scale=15), nullable=False),
    sa.Column('dropoff_latitude', sa.DECIMAL(precision=18, scale=15), nullable=False),
    sa.Column('passenger_count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxi_fare')
    # ### end Alembic commands ###
